### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Mahasri01** [Pradeeppk7/Gymapplication#1]
![image](https://user-images.githubusercontent.com/102822683/166163602-400f55da-e301-4d22-9c87-24eb5e18572a.png)
I'm getting a issue in register as well as login page

**Comment by Pradeeppk7** [comment]
The back end has been expired..
Create your own database in mongodb and edit in backend

**Comment by Mahasri01** [comment]
Could you please explain steps to connect mongodb with angular?

**Comment by Mahasri01** [comment]
I'm getting these kind of errors pls help to resolve
![Screenshot (975)](https://user-images.githubusercontent.com/102822683/166190473-791cbc18-5b0a-4790-b13b-d178efc65ab3.png)
![Screenshot (976)](https://user-images.githubusercontent.com/102822683/166190479-a5c5fa68-31a8-4f7a-9534-e3a15bd77800.png)
![Screenshot (977)](https://user-images.githubusercontent.com/102822683/166190481-2afe9290-3036-432a-b8f3-0e747ffb161e.png)

**Comment by Pradeeppk7** [comment]
MongoDB has been extended , try again now.

**Comment by Pradeeppk7** [comment]
use this command "nodemon server.js" in another  shell

**Comment by Pradeeppk7** [comment]
Kindly match Your angular version 

![image](https://user-images.githubusercontent.com/88220620/166192270-83d8d281-8219-43c7-a603-cacc09c74638.png)

**Comment by Pradeeppk7** [comment]
In case of different version , use the below and downgrade the version.
ng --version
npm uninstall -g @angular/cli
npm cache clean --force

npm install -g @angular/cli@12.2.9
ng --version

**Comment by Pradeeppk7** [comment]
In case of further issue , DM in Instagram pradeep_pk7

**Comment by Mahasri01** [comment]
![image](https://user-images.githubusercontent.com/102822683/166193894-7157a60f-02cd-416c-89b2-1e419bf161a8.png)
I'm having the same angular version.

**Comment by Pradeeppk7** [comment]
npm i nodemon 
nodemon server.js

**Comment by Pradeeppk7** [comment]
Your node version is latest, try a lower version  of  14.18.0

**Comment by Mahasri01** [comment]
![image](https://user-images.githubusercontent.com/102822683/166197684-fe339d54-f06d-4d3f-980b-2dfed784641f.png)
![image](https://user-images.githubusercontent.com/102822683/166197715-67bcd4ed-2e1c-4586-8a4e-a183c9392e95.png)
Thank you so much for your immediate responses and  all errors has been rectified..

**Comment by Pradeeppk7** [comment]
Your welcome :)
